# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f17c51de0985663bbbd6ccd91d2589425ac8f64a5a70318d4d31e2d54114048a448c85ca549b15101587df69eec3f14a75e89450acc8fd4164bd7f97e056efe

test:
  secret_key_base: d6230e1167e82758a4d9d9766dd29e997c3904a40ba1a70c90acaebc22c7836b278617a43a69eb36b049a41c06b86e4a48d67b1944513d7a76ba5da11e6a52ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
